# Generated by Django 2.2.1 on 2019-05-28 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20190527_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.Brand'),
        ),
    ]
